
import { Pokemon } from "../pokemon/types";

// Generation 7 Pokemon (722-809)
export const gen7Pokemon: Pokemon[] = [
  {
    id: 722,
    name: "Rowlet",
    baseAttack: 107,
    baseDefense: 78,
    baseStamina: 155,
    types: ["Grass", "Flying"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/722.png",
  },
  {
    id: 723,
    name: "Dartrix",
    baseAttack: 145,
    baseDefense: 107,
    baseStamina: 186,
    types: ["Grass", "Flying"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/723.png",
  },
  {
    id: 724,
    name: "Decidueye",
    baseAttack: 210,
    baseDefense: 179,
    baseStamina: 207,
    types: ["Grass", "Ghost"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/724.png",
  },
  {
    id: 725,
    name: "Litten",
    baseAttack: 128,
    baseDefense: 63,
    baseStamina: 150,
    types: ["Fire"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/725.png",
  },
  {
    id: 726,
    name: "Torracat",
    baseAttack: 174,
    baseDefense: 103,
    baseStamina: 186,
    types: ["Fire"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/726.png",
  },
  {
    id: 727,
    name: "Incineroar",
    baseAttack: 214,
    baseDefense: 175,
    baseStamina: 216,
    types: ["Fire", "Dark"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/727.png",
  },
  {
    id: 728,
    name: "Popplio",
    baseAttack: 120,
    baseDefense: 69,
    baseStamina: 163,
    types: ["Water"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/728.png",
  },
  {
    id: 729,
    name: "Brionne",
    baseAttack: 168,
    baseDefense: 112,
    baseStamina: 184,
    types: ["Water"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/729.png",
  },
  {
    id: 730,
    name: "Primarina",
    baseAttack: 232,
    baseDefense: 195,
    baseStamina: 204,
    types: ["Water", "Fairy"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/730.png",
  },
  {
    id: 731,
    name: "Pikipek",
    baseAttack: 136,
    baseDefense: 59,
    baseStamina: 111,
    types: ["Normal", "Flying"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/731.png",
  },
  {
    id: 732,
    name: "Trumbeak",
    baseAttack: 159,
    baseDefense: 100,
    baseStamina: 146,
    types: ["Normal", "Flying"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/732.png",
  },
  {
    id: 733,
    name: "Toucannon",
    baseAttack: 222,
    baseDefense: 146,
    baseStamina: 190,
    types: ["Normal", "Flying"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/733.png",
  },
  {
    id: 734,
    name: "Yungoos",
    baseAttack: 122,
    baseDefense: 56,
    baseStamina: 134,
    types: ["Normal"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/734.png",
  },
  {
    id: 735,
    name: "Gumshoos",
    baseAttack: 194,
    baseDefense: 113,
    baseStamina: 204,
    types: ["Normal"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/735.png",
  },
  {
    id: 736,
    name: "Grubbin",
    baseAttack: 115,
    baseDefense: 85,
    baseStamina: 132,
    types: ["Bug"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/736.png",
  },
  {
    id: 737,
    name: "Charjabug",
    baseAttack: 145,
    baseDefense: 161,
    baseStamina: 149,
    types: ["Bug", "Electric"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/737.png",
  },
  {
    id: 738,
    name: "Vikavolt",
    baseAttack: 254,
    baseDefense: 158,
    baseStamina: 184,
    types: ["Bug", "Electric"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/738.png",
  },
  {
    id: 739,
    name: "Crabrawler",
    baseAttack: 150,
    baseDefense: 104,
    baseStamina: 132,
    types: ["Fighting"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/739.png",
  },
  {
    id: 740,
    name: "Crabominable",
    baseAttack: 231,
    baseDefense: 138,
    baseStamina: 219,
    types: ["Fighting", "Ice"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/740.png",
  },
  {
    id: 741,
    name: "Oricorio",
    baseAttack: 196,
    baseDefense: 145,
    baseStamina: 181,
    types: ["Fire", "Flying"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/741.png",
  },
  {
    id: 742,
    name: "Cutiefly",
    baseAttack: 110,
    baseDefense: 81,
    baseStamina: 120,
    types: ["Bug", "Fairy"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/742.png",
  },
  {
    id: 743,
    name: "Ribombee",
    baseAttack: 198,
    baseDefense: 146,
    baseStamina: 155,
    types: ["Bug", "Fairy"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/743.png",
  },
  {
    id: 744,
    name: "Rockruff",
    baseAttack: 117,
    baseDefense: 78,
    baseStamina: 128,
    types: ["Rock"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/744.png",
  },
  {
    id: 745,
    name: "Lycanroc",
    baseAttack: 231,
    baseDefense: 140,
    baseStamina: 181,
    types: ["Rock"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/745.png",
  },
  {
    id: 746,
    name: "Wishiwashi",
    baseAttack: 46,
    baseDefense: 43,
    baseStamina: 128,
    types: ["Water"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/746.png",
  },
  {
    id: 747,
    name: "Mareanie",
    baseAttack: 98,
    baseDefense: 110,
    baseStamina: 137,
    types: ["Poison", "Water"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/747.png",
  },
  {
    id: 748,
    name: "Toxapex",
    baseAttack: 114,
    baseDefense: 273,
    baseStamina: 137,
    types: ["Poison", "Water"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/748.png",
  },
  {
    id: 749,
    name: "Mudbray",
    baseAttack: 175,
    baseDefense: 121,
    baseStamina: 155,
    types: ["Ground"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/749.png",
  },
  {
    id: 750,
    name: "Mudsdale",
    baseAttack: 214,
    baseDefense: 174,
    baseStamina: 225,
    types: ["Ground"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/750.png",
  },
  {
    id: 751,
    name: "Dewpider",
    baseAttack: 72,
    baseDefense: 117,
    baseStamina: 134,
    types: ["Water", "Bug"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/751.png",
  },
  {
    id: 752,
    name: "Araquanid",
    baseAttack: 126,
    baseDefense: 219,
    baseStamina: 169,
    types: ["Water", "Bug"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/752.png",
  },
  {
    id: 753,
    name: "Fomantis",
    baseAttack: 100,
    baseDefense: 91,
    baseStamina: 120,
    types: ["Grass"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/753.png",
  },
  {
    id: 754,
    name: "Lurantis",
    baseAttack: 192,
    baseDefense: 169,
    baseStamina: 172,
    types: ["Grass"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/754.png",
  },
  {
    id: 755,
    name: "Morelull",
    baseAttack: 108,
    baseDefense: 119,
    baseStamina: 120,
    types: ["Grass", "Fairy"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/755.png",
  },
  {
    id: 756,
    name: "Shiinotic",
    baseAttack: 154,
    baseDefense: 168,
    baseStamina: 155,
    types: ["Grass", "Fairy"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/756.png",
  },
  {
    id: 757,
    name: "Salandit",
    baseAttack: 136,
    baseDefense: 80,
    baseStamina: 134,
    types: ["Poison", "Fire"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/757.png",
  },
  {
    id: 758,
    name: "Salazzle",
    baseAttack: 228,
    baseDefense: 130,
    baseStamina: 169,
    types: ["Poison", "Fire"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/758.png",
  },
  {
    id: 759,
    name: "Stufful",
    baseAttack: 136,
    baseDefense: 95,
    baseStamina: 172,
    types: ["Normal", "Fighting"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/759.png",
  },
  {
    id: 760,
    name: "Bewear",
    baseAttack: 226,
    baseDefense: 141,
    baseStamina: 260,
    types: ["Normal", "Fighting"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/760.png",
  },
  {
    id: 761,
    name: "Bounsweet",
    baseAttack: 55,
    baseDefense: 69,
    baseStamina: 123,
    types: ["Grass"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/761.png",
  },
  {
    id: 762,
    name: "Steenee",
    baseAttack: 78,
    baseDefense: 94,
    baseStamina: 141,
    types: ["Grass"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/762.png",
  },
  {
    id: 763,
    name: "Tsareena",
    baseAttack: 222,
    baseDefense: 195,
    baseStamina: 176,
    types: ["Grass"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/763.png",
  },
  {
    id: 764,
    name: "Comfey",
    baseAttack: 165,
    baseDefense: 215,
    baseStamina: 139,
    types: ["Fairy"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/764.png",
  },
  {
    id: 765,
    name: "Oranguru",
    baseAttack: 168,
    baseDefense: 192,
    baseStamina: 207,
    types: ["Normal", "Psychic"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/765.png",
  },
  {
    id: 766,
    name: "Passimian",
    baseAttack: 222,
    baseDefense: 160,
    baseStamina: 225,
    types: ["Fighting"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/766.png",
  },
  {
    id: 767,
    name: "Wimpod",
    baseAttack: 67,
    baseDefense: 74,
    baseStamina: 93,
    types: ["Bug", "Water"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/767.png",
  },
  {
    id: 768,
    name: "Golisopod",
    baseAttack: 218,
    baseDefense: 226,
    baseStamina: 181,
    types: ["Bug", "Water"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/768.png",
  },
  {
    id: 769,
    name: "Sandygast",
    baseAttack: 120,
    baseDefense: 118,
    baseStamina: 146,
    types: ["Ghost", "Ground"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/769.png",
  },
  {
    id: 770,
    name: "Palossand",
    baseAttack: 178,
    baseDefense: 178,
    baseStamina: 198,
    types: ["Ghost", "Ground"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/770.png",
  },
  {
    id: 771,
    name: "Pyukumuku",
    baseAttack: 97,
    baseDefense: 224,
    baseStamina: 146,
    types: ["Water"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/771.png",
  },
  {
    id: 772,
    name: "Type: Null",
    baseAttack: 184,
    baseDefense: 184,
    baseStamina: 216,
    types: ["Normal"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/772.png",
  },
  {
    id: 773,
    name: "Silvally",
    baseAttack: 198,
    baseDefense: 198,
    baseStamina: 216,
    types: ["Normal"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/773.png",
  },
  {
    id: 774,
    name: "Minior",
    baseAttack: 116,
    baseDefense: 192,
    baseStamina: 155,
    types: ["Rock", "Flying"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/774.png",
  },
  {
    id: 775,
    name: "Komala",
    baseAttack: 162,
    baseDefense: 162,
    baseStamina: 163,
    types: ["Normal"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/775.png",
  },
  {
    id: 776,
    name: "Turtonator",
    baseAttack: 165,
    baseDefense: 215,
    baseStamina: 155,
    types: ["Fire", "Dragon"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/776.png",
  },
  {
    id: 777,
    name: "Togedemaru",
    baseAttack: 190,
    baseDefense: 145,
    baseStamina: 163,
    types: ["Electric", "Steel"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/777.png",
  },
  {
    id: 778,
    name: "Mimikyu",
    baseAttack: 177,
    baseDefense: 199,
    baseStamina: 146,
    types: ["Ghost", "Fairy"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/778.png",
  },
  {
    id: 779,
    name: "Bruxish",
    baseAttack: 208,
    baseDefense: 145,
    baseStamina: 169,
    types: ["Water", "Psychic"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/779.png",
  },
  {
    id: 780,
    name: "Drampa",
    baseAttack: 231,
    baseDefense: 164,
    baseStamina: 186,
    types: ["Normal", "Dragon"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/780.png",
  },
  {
    id: 781,
    name: "Dhelmise",
    baseAttack: 233,
    baseDefense: 179,
    baseStamina: 172,
    types: ["Ghost", "Grass"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/781.png",
  },
  {
    id: 782,
    name: "Jangmo-o",
    baseAttack: 102,
    baseDefense: 108,
    baseStamina: 128,
    types: ["Dragon"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/782.png",
  },
  {
    id: 783,
    name: "Hakamo-o",
    baseAttack: 145,
    baseDefense: 162,
    baseStamina: 146,
    types: ["Dragon", "Fighting"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/783.png",
  },
  {
    id: 784,
    name: "Kommo-o",
    baseAttack: 222,
    baseDefense: 240,
    baseStamina: 181,
    types: ["Dragon", "Fighting"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/784.png",
  },
  {
    id: 785,
    name: "Tapu Koko",
    baseAttack: 250,
    baseDefense: 181,
    baseStamina: 172,
    types: ["Electric", "Fairy"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/785.png",
  },
  {
    id: 786,
    name: "Tapu Lele",
    baseAttack: 259,
    baseDefense: 208,
    baseStamina: 172,
    types: ["Psychic", "Fairy"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/786.png",
  },
  {
    id: 787,
    name: "Tapu Bulu",
    baseAttack: 249,
    baseDefense: 215,
    baseStamina: 172,
    types: ["Grass", "Fairy"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/787.png",
  },
  {
    id: 788,
    name: "Tapu Fini",
    baseAttack: 189,
    baseDefense: 254,
    baseStamina: 172,
    types: ["Water", "Fairy"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/788.png",
  },
  {
    id: 789,
    name: "Cosmog",
    baseAttack: 54,
    baseDefense: 57,
    baseStamina: 125,
    types: ["Psychic"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/789.png",
  },
  {
    id: 790,
    name: "Cosmoem",
    baseAttack: 54,
    baseDefense: 242,
    baseStamina: 125,
    types: ["Psychic"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/790.png",
  },
  {
    id: 791,
    name: "Solgaleo",
    baseAttack: 255,
    baseDefense: 191,
    baseStamina: 264,
    types: ["Psychic", "Steel"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/791.png",
  },
  {
    id: 792,
    name: "Lunala",
    baseAttack: 255,
    baseDefense: 191,
    baseStamina: 264,
    types: ["Psychic", "Ghost"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/792.png",
  },
  {
    id: 793,
    name: "Nihilego",
    baseAttack: 249,
    baseDefense: 210,
    baseStamina: 240,
    types: ["Rock", "Poison"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/793.png",
  },
  {
    id: 794,
    name: "Buzzwole",
    baseAttack: 236,
    baseDefense: 196,
    baseStamina: 216,
    types: ["Bug", "Fighting"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/794.png",
  },
  {
    id: 795,
    name: "Pheromosa",
    baseAttack: 316,
    baseDefense: 85,
    baseStamina: 174,
    types: ["Bug", "Fighting"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/795.png",
  },
  {
    id: 796,
    name: "Xurkitree",
    baseAttack: 330,
    baseDefense: 144,
    baseStamina: 195,
    types: ["Electric"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/796.png",
  },
  {
    id: 797,
    name: "Celesteela",
    baseAttack: 207,
    baseDefense: 199,
    baseStamina: 219,
    types: ["Steel", "Flying"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/797.png",
  },
  {
    id: 798,
    name: "Kartana",
    baseAttack: 323,
    baseDefense: 182,
    baseStamina: 139,
    types: ["Grass", "Steel"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/798.png",
  },
  {
    id: 799,
    name: "Guzzlord",
    baseAttack: 188,
    baseDefense: 99,
    baseStamina: 440,
    types: ["Dark", "Dragon"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/799.png",
  },
  {
    id: 800,
    name: "Necrozma",
    baseAttack: 277,
    baseDefense: 193,
    baseStamina: 219,
    types: ["Psychic"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/800.png",
  },
  {
    id: 801,
    name: "Magearna",
    baseAttack: 246,
    baseDefense: 225,
    baseStamina: 190,
    types: ["Steel", "Fairy"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/801.png",
  },
  {
    id: 802,
    name: "Marshadow",
    baseAttack: 265,
    baseDefense: 190,
    baseStamina: 207,
    types: ["Fighting", "Ghost"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/802.png",
  },
  {
    id: 803,
    name: "Poipole",
    baseAttack: 145,
    baseDefense: 133,
    baseStamina: 155,
    types: ["Poison"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/803.png",
  },
  {
    id: 804,
    name: "Naganadel",
    baseAttack: 263,
    baseDefense: 159,
    baseStamina: 177,
    types: ["Poison", "Dragon"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/804.png",
  },
  {
    id: 805,
    name: "Stakataka",
    baseAttack: 213,
    baseDefense: 298,
    baseStamina: 156,
    types: ["Rock", "Steel"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/805.png",
  },
  {
    id: 806,
    name: "Blacephalon",
    baseAttack: 315,
    baseDefense: 148,
    baseStamina: 142,
    types: ["Fire", "Ghost"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/806.png",
  },
  {
    id: 807,
    name: "Zeraora",
    baseAttack: 252,
    baseDefense: 177,
    baseStamina: 190,
    types: ["Electric"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/807.png",
  },
  {
    id: 808,
    name: "Meltan",
    baseAttack: 118,
    baseDefense: 99,
    baseStamina: 130,
    types: ["Steel"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/808.png",
  },
  {
    id: 809,
    name: "Melmetal",
    baseAttack: 226,
    baseDefense: 190,
    baseStamina: 264,
    types: ["Steel"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/809.png",
  },
];
