
import { Pokemon } from "../pokemon/types";

// Generation 8 Pokemon (810-905)
export const gen8Pokemon: Pokemon[] = [
  {
    id: 810,
    name: "Grookey",
    baseAttack: 122,
    baseDefense: 91,
    baseStamina: 137,
    types: ["Grass"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/810.png",
  },
  {
    id: 811,
    name: "Thwackey",
    baseAttack: 165,
    baseDefense: 134,
    baseStamina: 172,
    types: ["Grass"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/811.png",
  },
  {
    id: 812,
    name: "Rillaboom",
    baseAttack: 239,
    baseDefense: 168,
    baseStamina: 225,
    types: ["Grass"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/812.png",
  },
  {
    id: 813,
    name: "Scorbunny",
    baseAttack: 132,
    baseDefense: 79,
    baseStamina: 137,
    types: ["Fire"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/813.png",
  },
  {
    id: 814,
    name: "Raboot",
    baseAttack: 170,
    baseDefense: 125,
    baseStamina: 163,
    types: ["Fire"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/814.png",
  },
  {
    id: 815,
    name: "Cinderace",
    baseAttack: 253,
    baseDefense: 163,
    baseStamina: 190,
    types: ["Fire"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/815.png",
  },
  {
    id: 816,
    name: "Sobble",
    baseAttack: 132,
    baseDefense: 79,
    baseStamina: 137,
    types: ["Water"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/816.png",
  },
  {
    id: 817,
    name: "Drizzile",
    baseAttack: 186,
    baseDefense: 113,
    baseStamina: 163,
    types: ["Water"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/817.png",
  },
  {
    id: 818,
    name: "Inteleon",
    baseAttack: 262,
    baseDefense: 142,
    baseStamina: 172,
    types: ["Water"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/818.png",
  },
  {
    id: 819,
    name: "Skwovet",
    baseAttack: 95,
    baseDefense: 86,
    baseStamina: 172,
    types: ["Normal"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/819.png",
  },
  {
    id: 820,
    name: "Greedent",
    baseAttack: 160,
    baseDefense: 156,
    baseStamina: 260,
    types: ["Normal"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/820.png",
  },
  {
    id: 821,
    name: "Rookidee",
    baseAttack: 88,
    baseDefense: 67,
    baseStamina: 116,
    types: ["Flying"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/821.png",
  },
  {
    id: 822,
    name: "Corvisquire",
    baseAttack: 129,
    baseDefense: 110,
    baseStamina: 169,
    types: ["Flying"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/822.png",
  },
  {
    id: 823,
    name: "Corviknight",
    baseAttack: 163,
    baseDefense: 192,
    baseStamina: 221,
    types: ["Flying", "Steel"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/823.png",
  },
  {
    id: 824,
    name: "Blipbug",
    baseAttack: 46,
    baseDefense: 67,
    baseStamina: 93,
    types: ["Bug"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/824.png",
  },
  {
    id: 825,
    name: "Dottler",
    baseAttack: 87,
    baseDefense: 157,
    baseStamina: 137,
    types: ["Bug", "Psychic"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/825.png",
  },
  {
    id: 826,
    name: "Orbeetle",
    baseAttack: 156,
    baseDefense: 240,
    baseStamina: 155,
    types: ["Bug", "Psychic"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/826.png",
  },
  {
    id: 827,
    name: "Nickit",
    baseAttack: 85,
    baseDefense: 82,
    baseStamina: 120,
    types: ["Dark"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/827.png",
  },
  {
    id: 828,
    name: "Thievul",
    baseAttack: 172,
    baseDefense: 164,
    baseStamina: 172,
    types: ["Dark"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/828.png",
  },
  {
    id: 829,
    name: "Gossifleur",
    baseAttack: 70,
    baseDefense: 104,
    baseStamina: 120,
    types: ["Grass"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/829.png",
  },
  {
    id: 830,
    name: "Eldegoss",
    baseAttack: 148,
    baseDefense: 211,
    baseStamina: 155,
    types: ["Grass"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/830.png",
  },
  {
    id: 831,
    name: "Wooloo",
    baseAttack: 76,
    baseDefense: 99,
    baseStamina: 123,
    types: ["Normal"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/831.png",
  },
  {
    id: 832,
    name: "Dubwool",
    baseAttack: 159,
    baseDefense: 198,
    baseStamina: 176,
    types: ["Normal"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/832.png",
  },
  {
    id: 833,
    name: "Chewtle",
    baseAttack: 114,
    baseDefense: 85,
    baseStamina: 137,
    types: ["Water"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/833.png",
  },
  {
    id: 834,
    name: "Drednaw",
    baseAttack: 213,
    baseDefense: 164,
    baseStamina: 207,
    types: ["Water", "Rock"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/834.png",
  },
  {
    id: 835,
    name: "Yamper",
    baseAttack: 80,
    baseDefense: 90,
    baseStamina: 153,
    types: ["Electric"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/835.png",
  },
  {
    id: 836,
    name: "Boltund",
    baseAttack: 197,
    baseDefense: 131,
    baseStamina: 170,
    types: ["Electric"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/836.png",
  },
  {
    id: 837,
    name: "Rolycoly",
    baseAttack: 73,
    baseDefense: 91,
    baseStamina: 102,
    types: ["Rock"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/837.png",
  },
  {
    id: 838,
    name: "Carkol",
    baseAttack: 114,
    baseDefense: 157,
    baseStamina: 172,
    types: ["Rock", "Fire"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/838.png",
  },
  {
    id: 839,
    name: "Coalossal",
    baseAttack: 146,
    baseDefense: 198,
    baseStamina: 242,
    types: ["Rock", "Fire"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/839.png",
  },
  {
    id: 840,
    name: "Applin",
    baseAttack: 71,
    baseDefense: 116,
    baseStamina: 120,
    types: ["Grass", "Dragon"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/840.png",
  },
  {
    id: 841,
    name: "Flapple",
    baseAttack: 214,
    baseDefense: 144,
    baseStamina: 172,
    types: ["Grass", "Dragon"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/841.png",
  },
  {
    id: 842,
    name: "Appletun",
    baseAttack: 178,
    baseDefense: 146,
    baseStamina: 242,
    types: ["Grass", "Dragon"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/842.png",
  },
  {
    id: 843,
    name: "Silicobra",
    baseAttack: 103,
    baseDefense: 123,
    baseStamina: 141,
    types: ["Ground"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/843.png",
  },
  {
    id: 844,
    name: "Sandaconda",
    baseAttack: 202,
    baseDefense: 207,
    baseStamina: 176,
    types: ["Ground"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/844.png",
  },
  {
    id: 845,
    name: "Cramorant",
    baseAttack: 173,
    baseDefense: 163,
    baseStamina: 172,
    types: ["Flying", "Water"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/845.png",
  },
  {
    id: 846,
    name: "Arrokuda",
    baseAttack: 118,
    baseDefense: 72,
    baseStamina: 121,
    types: ["Water"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/846.png",
  },
  {
    id: 847,
    name: "Barraskewda",
    baseAttack: 258,
    baseDefense: 127,
    baseStamina: 156,
    types: ["Water"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/847.png",
  },
  {
    id: 848,
    name: "Toxel",
    baseAttack: 97,
    baseDefense: 65,
    baseStamina: 120,
    types: ["Electric", "Poison"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/848.png",
  },
  {
    id: 849,
    name: "Toxtricity",
    baseAttack: 224,
    baseDefense: 140,
    baseStamina: 181,
    types: ["Electric", "Poison"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/849.png",
  },
  {
    id: 850,
    name: "Sizzlipede",
    baseAttack: 118,
    baseDefense: 90,
    baseStamina: 137,
    types: ["Fire", "Bug"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/850.png",
  },
  {
    id: 851,
    name: "Centiskorch",
    baseAttack: 220,
    baseDefense: 158,
    baseStamina: 225,
    types: ["Fire", "Bug"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/851.png",
  },
  {
    id: 852,
    name: "Clobbopus",
    baseAttack: 121,
    baseDefense: 103,
    baseStamina: 137,
    types: ["Fighting"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/852.png",
  },
  {
    id: 853,
    name: "Grapploct",
    baseAttack: 209,
    baseDefense: 162,
    baseStamina: 190,
    types: ["Fighting"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/853.png",
  },
  {
    id: 854,
    name: "Sinistea",
    baseAttack: 134,
    baseDefense: 96,
    baseStamina: 120,
    types: ["Ghost"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/854.png",
  },
  {
    id: 855,
    name: "Polteageist",
    baseAttack: 248,
    baseDefense: 189,
    baseStamina: 155,
    types: ["Ghost"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/855.png",
  },
  {
    id: 856,
    name: "Hatenna",
    baseAttack: 98,
    baseDefense: 93,
    baseStamina: 123,
    types: ["Psychic"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/856.png",
  },
  {
    id: 857,
    name: "Hattrem",
    baseAttack: 153,
    baseDefense: 133,
    baseStamina: 149,
    types: ["Psychic"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/857.png",
  },
  {
    id: 858,
    name: "Hatterene",
    baseAttack: 237,
    baseDefense: 182,
    baseStamina: 149,
    types: ["Psychic", "Fairy"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/858.png",
  },
  {
    id: 859,
    name: "Impidimp",
    baseAttack: 103,
    baseDefense: 69,
    baseStamina: 128,
    types: ["Dark", "Fairy"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/859.png",
  },
  {
    id: 860,
    name: "Morgrem",
    baseAttack: 145,
    baseDefense: 102,
    baseStamina: 163,
    types: ["Dark", "Fairy"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/860.png",
  },
  {
    id: 861,
    name: "Grimmsnarl",
    baseAttack: 227,
    baseDefense: 139,
    baseStamina: 216,
    types: ["Dark", "Fairy"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/861.png",
  },
  {
    id: 862,
    name: "Obstagoon",
    baseAttack: 180,
    baseDefense: 194,
    baseStamina: 212,
    types: ["Dark", "Normal"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/862.png",
  },
  {
    id: 863,
    name: "Perrserker",
    baseAttack: 195,
    baseDefense: 162,
    baseStamina: 172,
    types: ["Steel"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/863.png",
  },
  {
    id: 864,
    name: "Cursola",
    baseAttack: 253,
    baseDefense: 182,
    baseStamina: 155,
    types: ["Ghost"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/864.png",
  },
  {
    id: 865,
    name: "Sirfetch'd",
    baseAttack: 248,
    baseDefense: 176,
    baseStamina: 158,
    types: ["Fighting"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/865.png",
  },
  {
    id: 866,
    name: "Mr. Rime",
    baseAttack: 212,
    baseDefense: 179,
    baseStamina: 190,
    types: ["Ice", "Psychic"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/866.png",
  },
  {
    id: 867,
    name: "Runerigus",
    baseAttack: 163,
    baseDefense: 237,
    baseStamina: 151,
    types: ["Ground", "Ghost"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/867.png",
  },
  {
    id: 868,
    name: "Milcery",
    baseAttack: 80,
    baseDefense: 105,
    baseStamina: 128,
    types: ["Fairy"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/868.png",
  },
  {
    id: 869,
    name: "Alcremie",
    baseAttack: 145,
    baseDefense: 216,
    baseStamina: 163,
    types: ["Fairy"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/869.png",
  },
  {
    id: 870,
    name: "Falinks",
    baseAttack: 193,
    baseDefense: 170,
    baseStamina: 163,
    types: ["Fighting"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/870.png",
  },
  {
    id: 871,
    name: "Pincurchin",
    baseAttack: 176,
    baseDefense: 161,
    baseStamina: 134,
    types: ["Electric"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/871.png",
  },
  {
    id: 872,
    name: "Snom",
    baseAttack: 76,
    baseDefense: 59,
    baseStamina: 102,
    types: ["Ice", "Bug"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/872.png",
  },
  {
    id: 873,
    name: "Frosmoth",
    baseAttack: 230,
    baseDefense: 155,
    baseStamina: 172,
    types: ["Ice", "Bug"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/873.png",
  },
  {
    id: 874,
    name: "Stonjourner",
    baseAttack: 222,
    baseDefense: 182,
    baseStamina: 225,
    types: ["Rock"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/874.png",
  },
  {
    id: 875,
    name: "Eiscue",
    baseAttack: 148,
    baseDefense: 195,
    baseStamina: 181,
    types: ["Ice"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/875.png",
  },
  {
    id: 876,
    name: "Indeedee",
    baseAttack: 208,
    baseDefense: 166,
    baseStamina: 155,
    types: ["Psychic", "Normal"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/876.png",
  },
  {
    id: 877,
    name: "Morpeko",
    baseAttack: 192,
    baseDefense: 121,
    baseStamina: 151,
    types: ["Electric", "Dark"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/877.png",
  },
  {
    id: 878,
    name: "Cufant",
    baseAttack: 140,
    baseDefense: 91,
    baseStamina: 176,
    types: ["Steel"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/878.png",
  },
  {
    id: 879,
    name: "Copperajah",
    baseAttack: 226,
    baseDefense: 126,
    baseStamina: 263,
    types: ["Steel"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/879.png",
  },
  {
    id: 880,
    name: "Dracozolt",
    baseAttack: 195,
    baseDefense: 165,
    baseStamina: 207,
    types: ["Electric", "Dragon"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/880.png",
  },
  {
    id: 881,
    name: "Arctozolt",
    baseAttack: 190,
    baseDefense: 166,
    baseStamina: 207,
    types: ["Electric", "Ice"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/881.png",
  },
  {
    id: 882,
    name: "Dracovish",
    baseAttack: 175,
    baseDefense: 185,
    baseStamina: 207,
    types: ["Water", "Dragon"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/882.png",
  },
  {
    id: 883,
    name: "Arctovish",
    baseAttack: 171,
    baseDefense: 185,
    baseStamina: 207,
    types: ["Water", "Ice"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/883.png",
  },
  {
    id: 884,
    name: "Duraludon",
    baseAttack: 239,
    baseDefense: 185,
    baseStamina: 172,
    types: ["Steel", "Dragon"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/884.png",
  },
  {
    id: 885,
    name: "Dreepy",
    baseAttack: 117,
    baseDefense: 61,
    baseStamina: 99,
    types: ["Dragon", "Ghost"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/885.png",
  },
  {
    id: 886,
    name: "Drakloak",
    baseAttack: 163,
    baseDefense: 105,
    baseStamina: 169,
    types: ["Dragon", "Ghost"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/886.png",
  },
  {
    id: 887,
    name: "Dragapult",
    baseAttack: 266,
    baseDefense: 170,
    baseStamina: 204,
    types: ["Dragon", "Ghost"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/887.png",
  },
  {
    id: 888,
    name: "Zacian",
    baseAttack: 254,
    baseDefense: 236,
    baseStamina: 192,
    types: ["Fairy"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/888.png",
  },
  {
    id: 889,
    name: "Zamazenta",
    baseAttack: 250,
    baseDefense: 240,
    baseStamina: 192,
    types: ["Fighting"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/889.png",
  },
  {
    id: 890,
    name: "Eternatus",
    baseAttack: 278,
    baseDefense: 192,
    baseStamina: 268,
    types: ["Poison", "Dragon"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/890.png",
  },
  {
    id: 891,
    name: "Kubfu",
    baseAttack: 170,
    baseDefense: 158,
    baseStamina: 155,
    types: ["Fighting"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/891.png",
  },
  {
    id: 892,
    name: "Urshifu",
    baseAttack: 254,
    baseDefense: 177,
    baseStamina: 225,
    types: ["Fighting", "Dark"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/892.png",
  },
  {
    id: 893,
    name: "Zarude",
    baseAttack: 242,
    baseDefense: 215,
    baseStamina: 233,
    types: ["Dark", "Grass"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/893.png",
  },
  {
    id: 894,
    name: "Regieleki",
    baseAttack: 253,
    baseDefense: 177,
    baseStamina: 190,
    types: ["Electric"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/894.png",
  },
  {
    id: 895,
    name: "Regidrago",
    baseAttack: 202,
    baseDefense: 189,
    baseStamina: 400,
    types: ["Dragon"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/895.png",
  },
  {
    id: 896,
    name: "Glastrier",
    baseAttack: 246,
    baseDefense: 223,
    baseStamina: 225,
    types: ["Ice"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/896.png",
  },
  {
    id: 897,
    name: "Spectrier",
    baseAttack: 273,
    baseDefense: 146,
    baseStamina: 205,
    types: ["Ghost"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/897.png",
  },
  {
    id: 898,
    name: "Calyrex",
    baseAttack: 162,
    baseDefense: 154,
    baseStamina: 225,
    types: ["Psychic", "Grass"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/898.png",
  },
  {
    id: 899,
    name: "Wyrdeer",
    baseAttack: 211,
    baseDefense: 193,
    baseStamina: 230,
    types: ["Normal", "Psychic"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/899.png",
  },
  {
    id: 900,
    name: "Kleavor",
    baseAttack: 240,
    baseDefense: 169,
    baseStamina: 198,
    types: ["Bug", "Rock"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/900.png",
  },
  {
    id: 901,
    name: "Ursaluna",
    baseAttack: 263,
    baseDefense: 185,
    baseStamina: 277,
    types: ["Ground", "Normal"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/901.png",
  },
  {
    id: 902,
    name: "Basculegion",
    baseAttack: 242,
    baseDefense: 152,
    baseStamina: 239,
    types: ["Water", "Ghost"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/902.png",
  },
  {
    id: 903,
    name: "Sneasler",
    baseAttack: 259,
    baseDefense: 158,
    baseStamina: 172,
    types: ["Fighting", "Poison"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/903.png",
  },
  {
    id: 904,
    name: "Overqwil",
    baseAttack: 243,
    baseDefense: 190,
    baseStamina: 195,
    types: ["Dark", "Poison"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/904.png",
  },
  {
    id: 905,
    name: "Enamorus",
    baseAttack: 267,
    baseDefense: 195,
    baseStamina: 198,
    types: ["Fairy", "Flying"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/905.png",
  },
];
