
import { Pokemon } from "../pokemon/types";

// Generation 9 Pokemon (906-1010)
export const gen9Pokemon: Pokemon[] = [
  {
    id: 906,
    name: "Sprigatito",
    baseAttack: 110,
    baseDefense: 84,
    baseStamina: 124,
    types: ["Grass"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/906.png",
  },
  {
    id: 907,
    name: "Floragato",
    baseAttack: 154,
    baseDefense: 118,
    baseStamina: 154,
    types: ["Grass"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/907.png",
  },
  {
    id: 908,
    name: "Meowscarada",
    baseAttack: 252,
    baseDefense: 152,
    baseStamina: 176,
    types: ["Grass", "Dark"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/908.png",
  },
  {
    id: 909,
    name: "Fuecoco",
    baseAttack: 108,
    baseDefense: 70,
    baseStamina: 155,
    types: ["Fire"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/909.png",
  },
  {
    id: 910,
    name: "Crocalor",
    baseAttack: 151,
    baseDefense: 111,
    baseStamina: 185,
    types: ["Fire"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/910.png",
  },
  {
    id: 911,
    name: "Skeledirge",
    baseAttack: 203,
    baseDefense: 188,
    baseStamina: 200,
    types: ["Fire", "Ghost"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/911.png",
  },
  {
    id: 912,
    name: "Quaxly",
    baseAttack: 110,
    baseDefense: 83,
    baseStamina: 135,
    types: ["Water"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/912.png",
  },
  {
    id: 913,
    name: "Quaxwell",
    baseAttack: 158,
    baseDefense: 120,
    baseStamina: 163,
    types: ["Water"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/913.png",
  },
  {
    id: 914,
    name: "Quaquaval",
    baseAttack: 245,
    baseDefense: 171,
    baseStamina: 197,
    types: ["Water", "Fighting"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/914.png",
  },
  {
    id: 915,
    name: "Lechonk",
    baseAttack: 80,
    baseDefense: 77,
    baseStamina: 146,
    types: ["Normal"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/915.png",
  },
  {
    id: 916,
    name: "Oinkologne",
    baseAttack: 171,
    baseDefense: 146,
    baseStamina: 254,
    types: ["Normal"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/916.png",
  },
  {
    id: 917,
    name: "Tarountula",
    baseAttack: 72,
    baseDefense: 92,
    baseStamina: 128,
    types: ["Bug"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/917.png",
  },
  {
    id: 918,
    name: "Spidops",
    baseAttack: 160,
    baseDefense: 176,
    baseStamina: 172,
    types: ["Bug"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/918.png",
  },
  {
    id: 919,
    name: "Nymble",
    baseAttack: 102,
    baseDefense: 59,
    baseStamina: 111,
    types: ["Bug"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/919.png",
  },
  {
    id: 920,
    name: "Lokix",
    baseAttack: 235,
    baseDefense: 115,
    baseStamina: 174,
    types: ["Bug", "Dark"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/920.png",
  },
  {
    id: 921,
    name: "Pawmi",
    baseAttack: 98,
    baseDefense: 65,
    baseStamina: 128,
    types: ["Electric"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/921.png",
  },
  {
    id: 922,
    name: "Pawmo",
    baseAttack: 142,
    baseDefense: 99,
    baseStamina: 155,
    types: ["Electric", "Fighting"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/922.png",
  },
  {
    id: 923,
    name: "Pawmot",
    baseAttack: 249,
    baseDefense: 150,
    baseStamina: 163,
    types: ["Electric", "Fighting"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/923.png",
  },
  {
    id: 924,
    name: "Tandemaus",
    baseAttack: 115,
    baseDefense: 82,
    baseStamina: 137,
    types: ["Normal"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/924.png",
  },
  {
    id: 925,
    name: "Maushold",
    baseAttack: 160,
    baseDefense: 102,
    baseStamina: 181,
    types: ["Normal"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/925.png",
  },
  {
    id: 926,
    name: "Fidough",
    baseAttack: 98,
    baseDefense: 93,
    baseStamina: 128,
    types: ["Fairy"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/926.png",
  },
  {
    id: 927,
    name: "Dachsbun",
    baseAttack: 164,
    baseDefense: 174,
    baseStamina: 172,
    types: ["Fairy"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/927.png",
  },
  {
    id: 928,
    name: "Smoliv",
    baseAttack: 65,
    baseDefense: 68,
    baseStamina: 121,
    types: ["Grass", "Normal"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/928.png",
  },
  {
    id: 929,
    name: "Dolliv",
    baseAttack: 125,
    baseDefense: 146,
    baseStamina: 146,
    types: ["Grass", "Normal"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/929.png",
  },
  {
    id: 930,
    name: "Arboliva",
    baseAttack: 208,
    baseDefense: 226,
    baseStamina: 163,
    types: ["Grass", "Normal"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/930.png",
  },
  {
    id: 931,
    name: "Squawkabilly",
    baseAttack: 171,
    baseDefense: 121,
    baseStamina: 172,
    types: ["Normal", "Flying"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/931.png",
  },
  {
    id: 932,
    name: "Nacli",
    baseAttack: 83,
    baseDefense: 111,
    baseStamina: 155,
    types: ["Rock"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/932.png",
  },
  {
    id: 933,
    name: "Naclstack",
    baseAttack: 127,
    baseDefense: 141,
    baseStamina: 172,
    types: ["Rock"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/933.png",
  },
  {
    id: 934,
    name: "Garganacl",
    baseAttack: 174,
    baseDefense: 200,
    baseStamina: 251,
    types: ["Rock"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/934.png",
  },
  {
    id: 935,
    name: "Charcadet",
    baseAttack: 109,
    baseDefense: 89,
    baseStamina: 120,
    types: ["Fire"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/935.png",
  },
  {
    id: 936,
    name: "Armarouge",
    baseAttack: 255,
    baseDefense: 188,
    baseStamina: 172,
    types: ["Fire", "Psychic"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/936.png",
  },
  {
    id: 937,
    name: "Ceruledge",
    baseAttack: 252,
    baseDefense: 172,
    baseStamina: 172,
    types: ["Fire", "Ghost"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/937.png",
  },
  {
    id: 938,
    name: "Tadbulb",
    baseAttack: 104,
    baseDefense: 71,
    baseStamina: 137,
    types: ["Electric"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/938.png",
  },
  {
    id: 939,
    name: "Bellibolt",
    baseAttack: 151,
    baseDefense: 181,
    baseStamina: 222,
    types: ["Electric"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/939.png",
  },
  {
    id: 940,
    name: "Wattrel",
    baseAttack: 114,
    baseDefense: 70,
    baseStamina: 120,
    types: ["Electric", "Flying"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/940.png",
  },
  {
    id: 941,
    name: "Kilowattrel",
    baseAttack: 221,
    baseDefense: 125,
    baseStamina: 169,
    types: ["Electric", "Flying"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/941.png",
  },
  {
    id: 942,
    name: "Maschiff",
    baseAttack: 121,
    baseDefense: 90,
    baseStamina: 172,
    types: ["Dark"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/942.png",
  },
  {
    id: 943,
    name: "Mabosstiff",
    baseAttack: 207,
    baseDefense: 159,
    baseStamina: 232,
    types: ["Dark"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/943.png",
  },
  {
    id: 944,
    name: "Shroodle",
    baseAttack: 139,
    baseDefense: 70,
    baseStamina: 120,
    types: ["Poison", "Normal"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/944.png",
  },
  {
    id: 945,
    name: "Grafaiai",
    baseAttack: 221,
    baseDefense: 136,
    baseStamina: 181,
    types: ["Poison", "Normal"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/945.png",
  },
  {
    id: 946,
    name: "Bramblin",
    baseAttack: 112,
    baseDefense: 83,
    baseStamina: 120,
    types: ["Grass", "Ghost"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/946.png",
  },
  {
    id: 947,
    name: "Brambleghast",
    baseAttack: 206,
    baseDefense: 179,
    baseStamina: 155,
    types: ["Grass", "Ghost"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/947.png",
  },
  {
    id: 948,
    name: "Toedscool",
    baseAttack: 83,
    baseDefense: 111,
    baseStamina: 111,
    types: ["Ground", "Grass"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/948.png",
  },
  {
    id: 949,
    name: "Toedscruel",
    baseAttack: 161,
    baseDefense: 198,
    baseStamina: 155,
    types: ["Ground", "Grass"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/949.png",
  },
  {
    id: 950,
    name: "Klawf",
    baseAttack: 171,
    baseDefense: 155,
    baseStamina: 172,
    types: ["Rock"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/950.png",
  },
  {
    id: 951,
    name: "Capsakid",
    baseAttack: 106,
    baseDefense: 96,
    baseStamina: 155,
    types: ["Grass"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/951.png",
  },
  {
    id: 952,
    name: "Scovillain",
    baseAttack: 225,
    baseDefense: 156,
    baseStamina: 181,
    types: ["Grass", "Fire"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/952.png",
  },
  {
    id: 953,
    name: "Rellor",
    baseAttack: 96,
    baseDefense: 115,
    baseStamina: 137,
    types: ["Bug"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/953.png",
  },
  {
    id: 954,
    name: "Rabsca",
    baseAttack: 187,
    baseDefense: 216,
    baseStamina: 155,
    types: ["Bug", "Psychic"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/954.png",
  },
  {
    id: 955,
    name: "Flittle",
    baseAttack: 112,
    baseDefense: 75,
    baseStamina: 128,
    types: ["Psychic"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/955.png",
  },
  {
    id: 956,
    name: "Espathra",
    baseAttack: 230,
    baseDefense: 137,
    baseStamina: 190,
    types: ["Psychic"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/956.png",
  },
  {
    id: 957,
    name: "Tinkatink",
    baseAttack: 88,
    baseDefense: 108,
    baseStamina: 120,
    types: ["Fairy", "Steel"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/957.png",
  },
  {
    id: 958,
    name: "Tinkatuff",
    baseAttack: 128,
    baseDefense: 158,
    baseStamina: 146,
    types: ["Fairy", "Steel"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/958.png",
  },
  {
    id: 959,
    name: "Tinkaton",
    baseAttack: 158,
    baseDefense: 226,
    baseStamina: 190,
    types: ["Fairy", "Steel"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/959.png",
  },
  {
    id: 960,
    name: "Wiglett",
    baseAttack: 109,
    baseDefense: 78,
    baseStamina: 120,
    types: ["Water"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/960.png",
  },
  {
    id: 961,
    name: "Wugtrio",
    baseAttack: 208,
    baseDefense: 166,
    baseStamina: 137,
    types: ["Water"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/961.png",
  },
  {
    id: 962,
    name: "Bombirdier",
    baseAttack: 203,
    baseDefense: 158,
    baseStamina: 190,
    types: ["Flying", "Dark"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/962.png",
  },
  {
    id: 963,
    name: "Finizen",
    baseAttack: 133,
    baseDefense: 96,
    baseStamina: 155,
    types: ["Water"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/963.png",
  },
  {
    id: 964,
    name: "Palafin",
    baseAttack: 160,
    baseDefense: 179,
    baseStamina: 229,
    types: ["Water"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/964.png",
  },
  {
    id: 965,
    name: "Varoom",
    baseAttack: 115,
    baseDefense: 100,
    baseStamina: 155,
    types: ["Steel", "Poison"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/965.png",
  },
  {
    id: 966,
    name: "Revavroom",
    baseAttack: 210,
    baseDefense: 178,
    baseStamina: 190,
    types: ["Steel", "Poison"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/966.png",
  },
  {
    id: 967,
    name: "Cyclizar",
    baseAttack: 175,
    baseDefense: 165,
    baseStamina: 172,
    types: ["Dragon", "Normal"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/967.png",
  },
  {
    id: 968,
    name: "Orthworm",
    baseAttack: 167,
    baseDefense: 211,
    baseStamina: 181,
    types: ["Steel"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/968.png",
  },
  {
    id: 969,
    name: "Glimmet",
    baseAttack: 120,
    baseDefense: 133,
    baseStamina: 128,
    types: ["Rock", "Poison"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/969.png",
  },
  {
    id: 970,
    name: "Glimmora",
    baseAttack: 196,
    baseDefense: 235,
    baseStamina: 181,
    types: ["Rock", "Poison"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/970.png",
  },
  {
    id: 971,
    name: "Greavard",
    baseAttack: 105,
    baseDefense: 103,
    baseStamina: 137,
    types: ["Ghost"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/971.png",
  },
  {
    id: 972,
    name: "Houndstone",
    baseAttack: 188,
    baseDefense: 176,
    baseStamina: 172,
    types: ["Ghost"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/972.png",
  },
  {
    id: 973,
    name: "Flamigo",
    baseAttack: 230,
    baseDefense: 151,
    baseStamina: 172,
    types: ["Flying", "Fighting"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/973.png",
  },
  {
    id: 974,
    name: "Cetoddle",
    baseAttack: 111,
    baseDefense: 111,
    baseStamina: 190,
    types: ["Ice"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/974.png",
  },
  {
    id: 975,
    name: "Cetitan",
    baseAttack: 208,
    baseDefense: 176,
    baseStamina: 329,
    types: ["Ice"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/975.png",
  },
  {
    id: 976,
    name: "Veluza",
    baseAttack: 223,
    baseDefense: 124,
    baseStamina: 172,
    types: ["Water", "Psychic"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/976.png",
  },
  {
    id: 977,
    name: "Dondozo",
    baseAttack: 188,
    baseDefense: 213,
    baseStamina: 329,
    types: ["Water"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/977.png",
  },
  {
    id: 978,
    name: "Tatsugiri",
    baseAttack: 223,
    baseDefense: 166,
    baseStamina: 146,
    types: ["Dragon", "Water"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/978.png",
  },
  {
    id: 979,
    name: "Annihilape",
    baseAttack: 219,
    baseDefense: 182,
    baseStamina: 207,
    types: ["Fighting", "Ghost"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/979.png",
  },
  {
    id: 980,
    name: "Clodsire",
    baseAttack: 174,
    baseDefense: 163,
    baseStamina: 242,
    types: ["Poison", "Ground"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/980.png",
  },
  {
    id: 981,
    name: "Farigiraf",
    baseAttack: 221,
    baseDefense: 164,
    baseStamina: 221,
    types: ["Normal", "Psychic"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/981.png",
  },
  {
    id: 982,
    name: "Dudunsparce",
    baseAttack: 160,
    baseDefense: 185,
    baseStamina: 225,
    types: ["Normal"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/982.png",
  },
  {
    id: 983,
    name: "Kingambit",
    baseAttack: 251,
    baseDefense: 240,
    baseStamina: 190,
    types: ["Dark", "Steel"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/983.png",
  },
  {
    id: 984,
    name: "Great Tusk",
    baseAttack: 248,
    baseDefense: 182,
    baseStamina: 242,
    types: ["Ground", "Fighting"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/984.png",
  },
  {
    id: 985,
    name: "Scream Tail",
    baseAttack: 173,
    baseDefense: 212,
    baseStamina: 207,
    types: ["Fairy", "Psychic"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/985.png",
  },
  {
    id: 986,
    name: "Brute Bonnet",
    baseAttack: 188,
    baseDefense: 212,
    baseStamina: 242,
    types: ["Grass", "Dark"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/986.png",
  },
  {
    id: 987,
    name: "Flutter Mane",
    baseAttack: 248,
    baseDefense: 152,
    baseStamina: 172,
    types: ["Ghost", "Fairy"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/987.png",
  },
  {
    id: 988,
    name: "Slither Wing",
    baseAttack: 248,
    baseDefense: 182,
    baseStamina: 207,
    types: ["Bug", "Fighting"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/988.png",
  },
  {
    id: 989,
    name: "Sandy Shocks",
    baseAttack: 248,
    baseDefense: 182,
    baseStamina: 172,
    types: ["Electric", "Ground"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/989.png",
  },
  {
    id: 990,
    name: "Iron Treads",
    baseAttack: 201,
    baseDefense: 227,
    baseStamina: 207,
    types: ["Ground", "Steel"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/990.png",
  },
  {
    id: 991,
    name: "Iron Bundle",
    baseAttack: 248,
    baseDefense: 182,
    baseStamina: 172,
    types: ["Ice", "Water"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/991.png",
  },
  {
    id: 992,
    name: "Iron Hands",
    baseAttack: 232,
    baseDefense: 176,
    baseStamina: 233,
    types: ["Fighting", "Electric"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/992.png",
  },
  {
    id: 993,
    name: "Iron Jugulis",
    baseAttack: 248,
    baseDefense: 182,
    baseStamina: 207,
    types: ["Dark", "Flying"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/993.png",
  },
  {
    id: 994,
    name: "Iron Moth",
    baseAttack: 248,
    baseDefense: 182,
    baseStamina: 172,
    types: ["Fire", "Poison"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/994.png",
  },
  {
    id: 995,
    name: "Iron Thorns",
    baseAttack: 232,
    baseDefense: 176,
    baseStamina: 225,
    types: ["Rock", "Electric"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/995.png",
  },
  {
    id: 996,
    name: "Frigibax",
    baseAttack: 102,
    baseDefense: 108,
    baseStamina: 137,
    types: ["Dragon", "Ice"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/996.png",
  },
  {
    id: 997,
    name: "Arctibax",
    baseAttack: 149,
    baseDefense: 163,
    baseStamina: 172,
    types: ["Dragon", "Ice"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/997.png",
  },
  {
    id: 998,
    name: "Baxcalibur",
    baseAttack: 254,
    baseDefense: 229,
    baseStamina: 230,
    types: ["Dragon", "Ice"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/998.png",
  },
  {
    id: 999,
    name: "Gimmighoul",
    baseAttack: 156,
    baseDefense: 155,
    baseStamina: 128,
    types: ["Ghost"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/999.png",
  },
  {
    id: 1000,
    name: "Gholdengo",
    baseAttack: 230,
    baseDefense: 219,
    baseStamina: 181,
    types: ["Steel", "Ghost"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1000.png",
  },
  {
    id: 1001,
    name: "Wo-Chien",
    baseAttack: 183,
    baseDefense: 235,
    baseStamina: 198,
    types: ["Dark", "Grass"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1001.png",
  },
  {
    id: 1002,
    name: "Chien-Pao",
    baseAttack: 254,
    baseDefense: 196,
    baseStamina: 198,
    types: ["Dark", "Ice"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1002.png",
  },
  {
    id: 1003,
    name: "Ting-Lu",
    baseAttack: 214,
    baseDefense: 236,
    baseStamina: 225,
    types: ["Dark", "Ground"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1003.png",
  },
  {
    id: 1004,
    name: "Chi-Yu",
    baseAttack: 275,
    baseDefense: 203,
    baseStamina: 172,
    types: ["Dark", "Fire"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1004.png",
  },
  {
    id: 1005,
    name: "Roaring Moon",
    baseAttack: 245,
    baseDefense: 175,
    baseStamina: 212,
    types: ["Dragon", "Dark"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1005.png",
  },
  {
    id: 1006,
    name: "Iron Valiant",
    baseAttack: 248,
    baseDefense: 182,
    baseStamina: 172,
    types: ["Fairy", "Fighting"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1006.png",
  },
  {
    id: 1007,
    name: "Koraidon",
    baseAttack: 245,
    baseDefense: 220,
    baseStamina: 256,
    types: ["Fighting", "Dragon"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1007.png",
  },
  {
    id: 1008,
    name: "Miraidon",
    baseAttack: 245,
    baseDefense: 185,
    baseStamina: 256,
    types: ["Electric", "Dragon"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1008.png",
  },
  {
    id: 1009,
    name: "Walking Wake",
    baseAttack: 245,
    baseDefense: 178,
    baseStamina: 181,
    types: ["Water", "Dragon"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1009.png",
  },
  {
    id: 1010,
    name: "Iron Leaves",
    baseAttack: 252,
    baseDefense: 176,
    baseStamina: 181,
    types: ["Grass", "Psychic"],
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1010.png",
  },
];
